# Generated by Django 6.0.4 on 2026-06-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('fidele', 'Fidèle'), ('responsable', 'Responsable'), ('secretaire', 'Secrétaire'), ('tresorier', 'Trésorier'), ('pretre', 'Prêtre'), ('admin', 'Administrateur')], default='fidele', max_length=20, verbose_name='Rôle'),
        ),
    ]
